name: Run Selenium Test Daily

on:
  schedule:
    - cron: "30 17 * * *"  # 11:00 PM IST (17:30 UTC)
  workflow_dispatch:

jobs:
  run-selenium-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1

      - name: Verify Chrome version
        run: google-chrome --version

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-${{ runner.os }}

      - name: Install ChromeDriver
        run: sudo apt-get install -y chromium-chromedriver

      - name: Run Selenium Test
        run: mvn test
